"""Add foreign keys to team_members

Revision ID: fe310109f4bf
Revises: fc1d72abc25b
Create Date: 2025-10-05 23:43:10.493058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe310109f4bf'
down_revision: Union[str, Sequence[str], None] = 'fc1d72abc25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    # ### end Alembic commands ###
